zeromq/netmq

src/NetMQ.Tests/NetMQ.Tests.csproj
src/NetMQ.Tests/PubSubTests.cs
src/NetMQ.Tests/XPubSubTests.cs

The behavior was not obvious from docs before testing and looking into the source.

Test multiple publishers and single/multiple subscribers.

---

src/NetMQ/zmq/Patterns/Utils/ArrayExtensions.cs
src/NetMQ/zmq/Patterns/Utils/Trie.cs

I've noticed that Unsubscribe operation is broken for both Sub and XSub sockets. When you make unsubscription you can break trie structure that handles subscriptions.
You can reproduce situation with the following simple app. I've just copied ArrayExtension and Trie classes to not depend on other code.
It adds several tokens to the Trie and prints Trie content. Then removes one token and prints again. You can see that Trie content becomes broken.
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
namespace Test
{
static class ArrayExtensions
{
public static T[] Resize<T>(this T[] src, int size, bool ended)
{
T[] dest;
if (size > src.Length) {
dest = new T[size];
if (ended)
Array.Copy(src, 0, dest, 0, src.Length);
else
Array.Copy(src, 0, …
```

Fix XSub subscriptions.

---

src/NetMQ.Tests/MonitorPollTests.cs
src/NetMQ/Monitoring/NetMQMonitor.cs

This fix will ensure that the NetMQMonitor can be Stopped/Disposed even if an exception is raised from the MonitoringSocket.
It would interesting to know why Disconnect fails in this specific case. I don't know the internals of NetMQ enough. Maybe it's the designed behavior. In any case the NetMQMonitor should always complete properly (setting IsRunning = false and isStoppedEvent).

Making sure that NetMQMonitor can always be stopped/disposed

---

src/NetMQ.Tests/PollerTests.cs

This test failed from time to time because it depends on how accurate the code is being cold. I simply the test so it won't be depended on accuracy.

simplfy two timers test

---

src/NetMQ/zmq/Utils/OpCode.cs

During a development with an Arm device and using Netmq, the device send an exception related to the use of a native call using mmap and the RDTSC instructions for x86. The problem is RDTSC don't exist in the ARM instructions set(must use a cycle counter at kernel leve in linux).   This happens when you implements a poller.
I applied a workaround, detecting if NetMQ is running in an Arm device, set the RSTSC delegate to a function that returns the current tick count that mono(and .Net) provides. I am planning to implement the native call in asm for the cycle counter but in this moment seems to be a little more complex for my current knowledge, but i am working on it.
The required asm calls are documented in this asm codefile:
https://github.com/prabindh/peemuperf/blob/master/v7_pmu.S
I …

Added ARM archictecture detection to avoid the native call error when RDTSC used

---

src/NetMQ/OutgoingSocketExtensions.cs

Are these extension method arguments supposed to be passed through to the underlying socket?

Bug fix in OutgoingSocketExtensions.SendMore overloads

---

src/NetMQ.Tests/PgmTests.cs
src/NetMQ/SocketOptions.cs
src/NetMQ/zmq/Enums.cs
src/NetMQ/zmq/Options.cs

This changes the public API, but in quite an obvious way. Instead the old symbols could also be retained and marked obsolete. Let me know if that's preferred and I'll update the PR.

Fix typo. Receivev* -> Receive*

---

src/NetMQ.Tests/ProxyTests.cs
src/NetMQ/Proxy.cs

This PR addresses #239, as well as a bug seen during that work where `ReceiveReady` event handlers were not removed.
I welcome all and any feedback on this PR.

Proxy: Bug fix, external Poller, more tests

---

README.md

Multiple Socket Polling (part 4) link was a duplicate, and
Sending From Multiple Sockets (part 5) was missing.

Fixed a duplicate link in README.md

---

.gitignore
src/NetMQ.Tests/NetMQ.Tests.csproj
src/NetMQ.Tests/SocketOptionsTests.cs
src/NetMQ.sln
src/NetMQ/NetMQTimer.cs
src/NetMQ/Poller.cs
src/NetMQ/SocketOptions.cs
src/NetMQ/zmq/Enums.cs
src/NetMQ/zmq/Options.cs
src/NetMQ/zmq/Patterns/Router.cs
src/NetMQ/zmq/Patterns/Stream.cs
src/NetMQ/zmq/Transports/Tcp/TcpAddress.cs
src/NetMQ/zmq/Utils/Poller.cs
src/Samples/Brokerless Reliability (Freelance Pattern)/Model One/Freelance.ModelOne.Server/Program.cs

Prompted by #252, this PR adds a unit test that runs through all socket options.
Doing so revealed that several getters/setters are not usable and always throw InvalidException. They have been commented out. @somdoron it'd be great if you could review this.
Another small fix is that Router and Stream were each using `new Random().Next()` for `m_nextPeerId`. Sockets created in quick succession this way would have the same values.
Some string messages were added to exceptions observed during testing.

Socket option test, fixes and other fixes

---

src/NetMQ/NetMQ.csproj

To get the most out of @JamesWHurst's hard work documenting the API, we should ship XML docs in the NuGet package as `NetMQ.XML`, sitting alongside `NetMQ.dll`.
I'm not sure exactly how the NuGet package is built, but this seems a likely part of the puzzle.
Relates to #273.

Generate XML documentation file for release builds.

---

src/NetMQ/Msg.cs

My bad. I took the annotation at face value. Discovered today that the value can be null (when writing identity), so fixed this up.

Fix recently broken null-test and use correct annotation.

---

src/Performance/NetMQ.SimpleTests/NetMQ.SimpleTests.csproj

This fixes error CA0053 where visual studio was unable to locate the
static analysis tools used by Code Analysis.

Fix code analysis paths

---

src/NetMQ/zmq/SessionBase.cs

When a remote connection is lost the identity is sent to the remote connection when the connection is reestablished.

Identity is sent on reconnect for StreamSocket.

---

src/NetMQ/NetMQSocket.cs
src/NetMQ/SocketOptions.cs
src/NetMQ/Sockets/SubscriberSocket.cs
src/NetMQ/Sockets/XPublisherSocket.cs
src/NetMQ/Sockets/XSubscriberSocket.cs
src/NetMQ/zmq/Enums.cs
src/NetMQ/zmq/Options.cs
src/NetMQ/zmq/Patterns/Router.cs
src/NetMQ/zmq/Patterns/Sub.cs
src/NetMQ/zmq/Patterns/XPub.cs
src/NetMQ/zmq/SocketBase.cs
src/NetMQ/zmq/Utils/Selector.cs

No public API uses this enum. Plural names are for `[Flags]` enums ([see](https://msdn.microsoft.com/en-us/library/4x252001(v=vs.71).aspx)).

Make ZmqSocketOptions internal and rename

---

src/NetMQ/NetMQScheduler.cs

Lets caller know if they are running on the scheduler's thread.

Add CanExecuteTaskInline property to scheduler

---

src/NetMQ/Poller.cs
src/NetMQ/Proxy.cs

After introducing support for external pollers in #239/#250 I tried to use one again today and found myself confused about their use.
This PR triggers an exception if either of the proxy's frontend or backend sockets have not been added to an external poller.

Throw when external Poller with Proxy used in an invalid way.

---

src/NetMQ/Core/Utils/PollerBase.cs
src/NetMQ/Poller.cs

While doing profiling usage of Any() surfaced as memory footprint in #Gen0. Since the support of explicit Count property is there it should be used instead.

Changed lists to use Count instead of Any

---

src/NetMQ/Core/Utils/Clock.cs
src/NetMQ/Core/Utils/OpCode.cs

The root cause was that RdtscOnArm was returning tick counts (milliseconds) and the throttling code was expecting high-resolution CPU timings. This caused the socket to be throttled virtually indefinitely (MaxCommandDelay = 3000000 milliseconds).
Simplified the ARM detection code to instead just set s_rdtscSupported = false which disables the throttle checking for ARM processors and removed associated code that was no longer used.

Found that when running pub/sub sockets on a Raspberry PI subscription requests were never processed.

---

src/NetMQ.Tests/BeaconTests.cs
src/NetMQ/Core/Utils/Selector.cs
src/NetMQ/NetMQSocket.cs
src/NetMQ/Poller.cs

Fix for issue #319.
Changed parameter of Selector.Select to long so it is not that easy to overflow and now TimeSpan.MinValue and TimeSpan.MaxValue can be safely used, even for Ticks property. This can be further improved by normalizing all inputs to ticks (1 tick is 10 micros I think). This will remove the reason of overflow during multiplication by 1000 (numbers are not realistic though), but it could also allow to go below 1 ms min.
* Negative values are considered to be infinite (-1 for socket api).
* If for some reason a unusual large timeout value is used function will do its work in chunks of Int32.MaxValue microseconds (~35min) and not break prematurely.
* Sleep was moved to poller, it seems like the only reason for it was to make sure timers fire as scheduled without spinning if …

Fixed timeout overflows on Selector and moved sleep to Poller.

---

src/NetMQ.Tests/EventDelegatorTests.cs
src/NetMQ.Tests/NetMQ.Tests.csproj
src/NetMQ.Tests/NetMQ3.5.Tests.csproj
src/NetMQ/EventDelegator.cs
src/NetMQ/InProcActors/Actor.cs
src/NetMQ/NetMQActor.cs
src/NetMQ/NetMQBeacon.cs

Following #344, here are some fixes to the use of internal `EventDelegatorHelper`.
1. Use correct events in all places
2. Fix resubscribe in place of unsubscribe
3. Fix bug in reference counting that prevents unsubscribe
In #344 we discussed removing `EventDelegatorHelper`. Looking at it a little further, it possibly makes a difference in [`NetMQSocket:275`](https://github.com/zeromq/netmq/blob/master/src/NetMQ/NetMQSocket.cs#L275) where the absence of a receive handler excludes the `PollEvents.PollIn` flag from being set.
@somdoron, if you still feel like removing this class, I will put together another PR. At least it seems that bugs are now fixed.

Bug fixes in use of EventDelegatorHelper<TArgs>

---

AUTHORS.md
src/NetMQ.Tests/ProxyTests.cs
src/NetMQ/Proxy.cs

In the proxy we can define a single control socket that messages are sent to. This PR lets us define separate sockets for each direction.

Define separate proxy control sockets for incoming and outgoing traffic

---

src/NetMQ/Core/Transports/ByteArraySegment.cs
src/NetMQ/Core/Transports/V2Decoder.cs

There is a mismatch with ZeroMQ concerning unsigned 8 byte integer being used for size of payload. Comment was saying exactly that, but long was used instead. I also added max value check for max byte array size with 56 elements less (https://msdn.microsoft.com/en-us/library/hh285054.aspx remarks). Constant should be placed better though. So basically I just made code up to date with zeromq c++ for the eight byte size payloads on v2 decoder.
Other decoders/encoders are worth checking out too I guess.

Fix for issue #225

---

src/NetMQ.Tests/PollerTests.cs
src/NetMQ/NetMQTimer.cs

The only the reset the timer interval is to disable and enable the timer.
Add a method called EnableAndReset that enable the timer if disabled and reset the interval.
Useful Example: when you use the timer to send heartbeat after you didn't get a message for X seconds. Each time you get a message you will just call EnableAndReset.

problem: no easy way to reset timer

---

src/NetMQ.QueuePerformance/NetMQ.QueuePerformance.csproj
src/NetMQ.QueuePerformance/Program.cs
src/NetMQ.QueuePerformance/Properties/AssemblyInfo.cs
src/NetMQ.Tests/NetMQ.Tests.csproj
src/NetMQ.Tests/NetMQQueueTests.cs
src/NetMQ.sln
src/NetMQ/NetMQ.csproj
src/NetMQ/NetMQQueue.cs

If you want to poll on both NetMQSockets and wait for messages from queue right now it is not possible.
NetMQQueue is new queue which can be added to a poller and to poll on. The queue is multi producer single consumer. Enqueueing is thread safe but dequeueing is not

Problem: no way to use any dotnet queue with Poller

---

src/NetMQ/Core/Transports/StreamEngine.cs
src/NetMQ/Core/Transports/Tcp/TcpConnector.cs

This change should handle a case, when company has a different policy on wifi and ethernet network. If specific connection is allowed on ethernet, but on wifi it's blocked by firewall outgoing rule policy, it generates access denied socket error. In this case reconnection should be allowed to establish connection again when user is back on ethernet - has set policy which allows it.

Allow reconnect on access denied socket error

---

src/NetMQ.Tests/RouterTests.cs
src/NetMQ.Tests/XPubSubTests.cs
src/NetMQ/Core/Patterns/XPub.cs
src/NetMQ/Core/ZmqSocketOption.cs
src/NetMQ/Msg.cs
src/NetMQ/SocketOptions.cs

These changes add a broadcast feature that is similar to SignalR's `Clients.Others`. If the broadcast option is enabled and an XSub socket sends a topic prefixed with `2`, then that socket will never be matched on a subsequent `Send` by XPub. With this feature it is easy to turn a XPub into a message bus, when N XSub clients send a message to every other one - without additional Dealer/Router socket and without complicated check if a sender receives its own message back.
Without `XPubBroadcast` set to true, there is no change in behavior, so this change is backward compatible.
This PR depends on #400. It also removes unneeded copying of data in XSub by using the offset feature from #400.

Broadcast feature for XPub socket

---

src/NetMQ.Tests/XPubSubTests.cs
src/NetMQ/Msg.cs

Re: your comment that Offset/Size is internal. In the test we use Skip(1).ToArray(), but this includes copying of bytes. In my real code I already need this method after we changed the prefix removal logic in #401.

Add TrimPrefix method

---

src/NetMQ/Core/Patterns/Utils/MultiTrie.cs
src/NetMQ/Core/Patterns/XPub.cs

Fix bug with disconnected subscribers. The pipe queue was keeping them, and automatic unsubscribe messages were failing in manual mode because m_lastPipe was not set correctly. "Tested in production." KeyValuePair is semantically correct, because each pipe is associated with a message. Also KVP is a struct, while built-in tuples are classes, so there is no object allocation.

Fix bug with disconnected subscribers.

---

src/NetMQ.Tests/SocketTests.cs
src/NetMQ/NetMQSocket.cs
src/NetMQ/Sockets/DealerSocket.cs
src/NetMQ/Sockets/PairSocket.cs
src/NetMQ/Sockets/PublisherSocket.cs
src/NetMQ/Sockets/PullSocket.cs
src/NetMQ/Sockets/PushSocket.cs
src/NetMQ/Sockets/RequestSocket.cs
src/NetMQ/Sockets/ResponseSocket.cs
src/NetMQ/Sockets/RouterSocket.cs
src/NetMQ/Sockets/StreamSocket.cs
src/NetMQ/Sockets/SubscriberSocket.cs
src/NetMQ/Sockets/XPublisherSocket.cs
src/NetMQ/Sockets/XSubscriberSocket.cs

like bind and connect methods, which can be multiple lines of code.
Solution: accept connection string parameter in the ctor. For example:
```csharp
/// <summary>
/// Create a new DealerSocket and attach socket to zero or more endpoints.               
/// </summary>                
/// <param name="connectionString">List of NetMQ endpoints, seperated by commas and prefixed by '@' (to bind the socket) or '>' (to connect the socket).
/// Default action is connect (if endpoint doesn't start with '@' or '>')</param>
/// <example><code>var socket = new DealerSocket(">tcp://127.0.0.1:5555,@127.0.0.1:55556");</code></example>                 
public DealerSocket(string connectionString = null)
```

problem: creating socket in NetMQ is verbose and require multiple of lines

---

src/NetMQ.Tests/NetMQ.Tests.csproj
src/NetMQ.Tests/NetMQ3.5.Tests.csproj
src/NetMQ.Tests/packages.NetMQ.Tests.config
src/NetMQ.Tests/packages.NetMQ3.5.Tests.config
src/NetMQ/NetMQ.csproj
src/NetMQ/NetMQ3.5.csproj

We had a mix of 0.1.17 and 0.1.18.
This meant the `3.3.3-rc2` NuGet package I created didn't work without assembly redirects. I've deleted that package from NuGet and pushed `3.3.3-rc3` instead.

Use consistent AsyncIO version across solution (0.1.18.0)

---

src/NetMQ/Core/Ctx.cs
src/NetMQ/NetMQConfig.cs
src/NetMQ/NetMQContext.cs

solution: allow context to terminate without waiting for sockets
For NetMQContext you can use the Block keyword.
When creating sockets without context this is the default behavior, as the context is disposed when application exists.
fixes #384

problem: context might block forever is socket is not disposed or linger is not zero

---

src/NetMQ.Zyre.Tests/ZreMsgTests.cs
src/NetMQ.Zyre/NetMQ.Zyre.csproj
src/NetMQ.Zyre/ZreMsg.cs
src/NetMQ.Zyre/packages.config
src/NetMQ.Zyre/zproto/Example.xml
src/NetMQ.Zyre/zproto/zproto_codec_cs.gsl
src/NetMQ.Zyre/zproto/zproto_lib_cs.gsl
src/NetMQ.Zyre/zproto/zre_msg.xml

@somdoron , I think NetMQ.zproto is wonderful.
But, if I read this correctly, there is quite a bit of work to do on zproto_codec_cs.gsl to be able to generate a clean ZreMsg.cs class (in particular, to handle the msg type).
Yet it seems to me that this work should be first, rather than "rolling by hand" the ZreMsg.cs class.
What do you recommend? Should @vadian and/or I dig into changing zproto_codec_cs.gsl, or leave it to you and continue ZreMsg.cs without zproto?
Thank you.

Upgraded zproto for NetMQ.Zyre

---

src/NetMQ/Core/Options.cs
src/NetMQ/Core/Pipe.cs
src/NetMQ/Core/SessionBase.cs
src/NetMQ/Core/SocketBase.cs
src/NetMQ/Core/ZmqSocketOption.cs
src/NetMQ/SocketOptions.cs

This is a pull request for recently opened issue: "False positive high-watermark check in Pipe class #459". 
The main idea of proposed fix is to give explicit access to low-watermark value via configuration. The default low-watermark calculation logic is still in place and will be used when setting is not explicitly defined (or contains incorrect value).

Add settings to define send/receive low-watermark value

---

src/NetMQ.Tests/NetMQPollerTest.cs
src/NetMQ/NetMQPoller.cs

This interface is used in several APIs where synchronisation is offered, especially those which have been around for a long time in the BCL such as WinForms, WebForms, System.Timers.Timer and System.Diagnostics.Process.
The implementation utilises the TaskScheduler, and as such is not available in the .NET 3.5 build.

Make NetMQPoller implement ISynchronizeInvoke.

---

docs/pub-sub.md

Default high water mark is 1000, it was mentioned as zero.
Fixes #506.

Default high water mark is 1000.

---

src/build.bat

Solution: Added src\build.bat that will build NetMQ using latest DevStudio installed
on machine that has a C# compiler.

Problem: NetMQ does not have a command line build script

---

src/build.bat

Solution: Added NuGet command to download referenced packages prior to build
This requires user to download https://nuget.org/nuget.exe or
if preferred, build at least one using DevStudio NetMQ.sln, which
automatically downloads the referenced packages. After that first
build, build.bat will work with no errors even if NuGet.exe is not
present.

Problem: build.bat may fail due to NuGet references

---

src/build.bat

Solution: corrected typo in comments
There were two: there was a stray close parenthesis after nuget.exe in URL
There was a comment line that started :; when it should have started ::.
Thanks C-RACK for noticing it.

Problem: typo in comments

---

src/NetMQ/Core/MonitorEvent.cs

When m_addr is null, still write zero string length.
Issue https://github.com/zeromq/netmq/issues/528

Write null string length still

---

src/NetMQ.Tests/ManualContextTerminationTests.cs
src/NetMQ.Tests/NetMQ.Tests.csproj
src/NetMQ/NetMQConfig.cs

This pull request, adds the ability to terminate and create the global NetMQ context. For this to happen a ManualTerminationTakeOver, must be called at least once. After this the developer is responsible for the life time control of the NetMQ context.
This is a requirement for Unity3D development where the Editor wasn't playing nice with the static global context, since after calling Play, the context isn't terminated (no application exit happens). This may also help in some extreme cases like using pythonnet with NetMQ inside a DCC app, like 3dsmax or maya, where there is need for more control over the life of the context.

Manual context termination

---

docs/introduction.md

Solution: fix broken links
by adding ".md" at the end of the referenced link.
e.g. from "[receiving and sending](receiving-sending)" to "[receiving and sending](receiving-sending.md)"

Problem: Links to references getting github.com 404 error

---

docs/message.md
docs/poller.md
docs/pub-sub.md
docs/transports.md
docs/xpub-xsub.md

Solution: fixed broken links by adding ".md" at the end of the referenced link.
Found more instances...

Problem: Problem: Links to references getting github.com 404 error

---

src/NetMQ/NetMQ.nuspec

It was set to NetMQ4 which change the name of the package on Nuget.

Set the title of the package to NetMQ

---

src/NetMQ/Core/Options.cs
src/NetMQ/Core/Transports/Pgm/PgmSender.cs
src/NetMQ/Core/ZmqSocketOption.cs
src/NetMQ/SocketOptions.cs

This is critical when using PGM through VPN tunnels.

Added support for controlling PGM_MaxTSDL.

---

src/NetMQ.Tests/NetMQPollerTest.cs

There was a timing issue - technically poller.Run code has run to completion, but the task needs to finish up to switch status

Fixed RemoveSocket test

---

.gitignore
src/NetMQ/NetMQPoller.cs

- Update docs, as per #619 
- Throw if disposing poller from poller thread, as per #619 
- Ignore .idea folder
- Allow specifying thread name in new `NetMQPoller.RunAsync` overload
- Fix minor double-dispose bug in poller
Combined diff is hard to read. Individual diffs should be clear. Please review before merge. Happy to remove commits as needed.

Some changes to poller

---

src/NetMQ/NetMQPoller.cs

I introduced this bug in #657 two weeks back. I think it's contributing to failures in #662.
I'm working separately to get both AppVeyor and Travis CI building properly again, so we don't ignore PR build failures.

Fix NetMQPoller bug

---

src/NetMQ/NetMQConfig.cs

- Annotate nullable field
- Avoid lock (double checked locking)
- Documentation tweaks
One question that might improve this PR. What is the expected `TimeSpan` value for infinite linger? The `System.Threading.Timeout` class has `InfiniteTimeSpan = new TimeSpan(0, 0, 0, 0, Timeout.Infinite)`, which basically is a `TimeSpan` with -1 milliseconds. This constant is not available in `net35`, but at least our docs should explain how to pass `-1` in `TimeSpan` form.
If someone can verify this is correct I'll update the PR.

NetMQConfig tweaks

---

src/NetMQ.Tests/NetMQPollerTest.cs
src/NetMQ/Core/Utils/StopSignaler.cs
src/NetMQ/ISocketPollable.cs
src/NetMQ/NetMQActor.cs
src/NetMQ/NetMQBeacon.cs
src/NetMQ/NetMQPoller.cs
src/NetMQ/NetMQQueue.cs
src/NetMQ/NetMQSocket.cs

This PR addresses #663. That issue discusses throwing when removing a disposed socket (both immediately and asynchronously). It is invalid for a disposed socket to exist within a poller at any time, so we can make additional checks.
There are three cases covered here:
- Remove a disposed ISocketPollable
- Add a disposed ISocketPollable (seems pretty unlikely, but it's cheap to check)
- Dispose a NetMQPoller that contains a disposed ISocketPollable
Corresponding unit tests have been added.

NetMQPoller throws when inner socket disposed

---

src/NetMQ/Core/Transports/Pgm/PgmSocket.cs
src/NetMQ/Core/Transports/Tcp/TcpAddress.cs
src/NetMQ/Core/Utils/Clock.cs
src/NetMQ/Core/Utils/OpCode.cs
src/NetMQ/Core/Utils/PollerBase.cs
src/NetMQ/NetMQ.csproj
src/NetMQ/NetMQBeacon.cs
src/NetMQ/NetMQException.cs
src/NetMQ/TaskThread.cs

Microsoft cheated with the System.Threading.Thread library: while it
is claimed that UWP implements .NET Standard 1.4 [0], and per the
listing at [1], System.Threading.Thread claims to support .NET
Standard 1.3, in reality the System.Threading.Thread package will
fail to install on UWP targets, despite them being fully .NET
Standard 1.3 complaint. If this were anyone else, the package would
probably not have been allowed to claim .NET Standard 1.3 support
in the nuspec listing.
As a result of this mess, for NetMQ to be usable under Universal
Windows Platform (i.e. Windows 10 and Windows 10 phone runtimes),
it is necessary to drop the dependency on System.Threading.Thread,
at least for this target. As a result, a new target has been added
to the project indepedendent from .NET Standard 1.3 …

Support for Universal Windows Platform apps

---

src/NetMQ/NetMQ.csproj

The package `System.Runtime.Loader` is not used and it forces the NetMQ package to netstandard 1.5 instead of 1.3.

Remove System.Runtime.Loader dependency

---

src/NetMQ/TaskThread.cs

IsBackground does not affect whether the thread runs synchronously
or not. It merely specifies whether the application will wait for
the thread to finish executing before exiting (by default it does).
Due to the implementation of tasks under UAP, this doesn't seem to have affected the behavior of netmq, but it should definitely be corrected.

Corrected misunderstanding of the IsBackground property for TaskThread/UAP

---

.travis.yml

`dotnet test` doesn't accept just a path to a project directory, [yet](https://github.com/Microsoft/vstest/issues/630). =D
Also, `--labels` isn't an option.

fix the travis build

---

src/NetMQ/TaskThread.cs

TaskThread is also available as a NuGet project for UAP clients [0],
NetMQ includes the same source so as to not have an external dependency.
The NetMQ version should be internal as it does not offer a stable
interface and is not for consumption outside of NetMQ.

Mark TaskThread implementation as internal

---

src/NetMQ/Core/MonitorEvent.cs

Like .NET Standard, UAP has also deprecated Marshal.SizeOf(typeof(T))
and recommends using Marshal.SizeOf<T>() instead.

Use Marshal.SizeOf<T> on UAP too

---

src/NetMQ.Tests/NetMQPollerTest.cs
src/NetMQ/NetMQPoller.cs

I've been looking at a problem where my unit tests would lock up on a call to:
NetMQ.NetMQConfig.Cleanup(true);
The root cause is that my code was explicitly stopping the Poller before removing the sockets; therefore, the calls to Remove are never executed, and the Cleanup call waits forever.
I suggest raising an exception if this occurs, to make it more easy to detect this scenario.

Raise an error if removing a socket or timer from a stopped poller

---

appveyor.yml
src/NetMQ-unix.sln
src/NetMQ.Tests/NetMQ.Tests-unix.csproj
src/NetMQ.Tests/PeerTests.cs
src/NetMQ/Core/Options.cs
src/NetMQ/Core/Patterns/Peer.cs
src/NetMQ/Core/Pipe.cs
src/NetMQ/Core/SessionBase.cs
src/NetMQ/Core/SocketBase.cs
src/NetMQ/Core/ZmqSocketOption.cs
src/NetMQ/NetMQ-unix.csproj
src/NetMQ/SocketOptions.cs
src/NetMQ/Sockets/PeerSocket.cs
src/NetMQ/ZmqSocketType.cs

you have to use a dealer socket for every connection you made.
With peer socket type, you can get routing id of the peer you just connected to and use one socket both for incoming connections and outgoing connections.

problem: developing peer to peer with current socket is hard

---

src/NetMQ/NetMQ-unix.csproj
src/NetMQ/NetMQ.csproj

Related to #767.
I upgrade AsyncIO version to 0.1.61. 
Unit tests seem to pass.

Upgrade AsyncIO version to 0.1.61

---

src/NetMQ/Msg.cs

I think the name 'i' is not good for understanding the purpose of the variable

 Rename variable name from 'i' to 'dstOffset'

---

src/NetMQ/NetMQ.csproj

This should complete the work for https://github.com/zeromq/netmq/issues/768

update asyncIO 0.1.69 with netstandard2.0 support

---

src/NetMQ/OutgoingSocketExtensions.cs
src/NetMQ/ReceivingSocketExtensions.cs
src/NetMQ/RoutingKey.cs

It is hard to use as key in dictionaries or list.
Solution: have a new type for routing key and accept sending and receiving it from socket

problem: Handling routing key as byte-array is too complicated

---

docs/poller.md

I had to do some testing to find the right syntax, when instances are held instead of used in a using like the examples.

Added details about dispose ordering

---

src/NetMQ.Tests/AsyncTests.cs
src/NetMQ/AsyncReceiveExtensions.cs
src/NetMQ/NetMQPoller.cs

(This PR is cherry-picked version of https://github.com/planetarium/netmq/pull/1)
This PR adds some feature to `NetMQ.AsyncReceiveExtensions` as below.
- Added `.RecevieMultipartMessageAsync()` to receive a multi part message easily.
- Added `CancellationToken` argument to async extension methods in `AsyncReceiveExtensions`. (resolves #813)
- Fixed `AsyncTest` to indicate assertion properly.
- Removed state check on `NetMQPoller.Stop()` to prevent freezing during unit testing.

Enhence AsyncReceiveExtension

---

src/NetMQ.sln.DotSettings
src/NetMQ/ISocketPollableCollection.cs
src/NetMQ/Monitoring/NetMQMonitor.cs

fixes #829 issue with NetMqMonitor backward compatibility.
I had to add `void RemoveAndDispose<T> to ISocketPollableCollection,` so monitor can call this method by interface, thus avoiding coupling to concrete NetMqPoller class.

fixes #829 issue with NetMqMonitor backward compatibility

---

src/NetMQ/Core/Options.cs
src/NetMQ/Core/Patterns/Pub.cs
src/NetMQ/Core/Patterns/Push.cs
src/NetMQ/Core/Pipe.cs
src/NetMQ/Core/SessionBase.cs
src/NetMQ/Core/SocketBase.cs

Solution: Pub (and Push) sockets should not delay termination and wait for delimiter, as they are not processing msgs

problem: Pub socket is not able to remove disconnected pipes

---

src/NetMQ/NetMQPoller.cs

Thread names on Linux (.NET 5) have a max length of 16 chars.

Shortened NetMQPoller thread name

---

src/NetMQ.Tests/SocketOptionsTests.cs
src/NetMQ/Core/HellloMsgSession.cs
src/NetMQ/Core/Options.cs
src/NetMQ/Core/Patterns/Dealer.cs
src/NetMQ/Core/Patterns/Pair.cs
src/NetMQ/Core/Patterns/Peer.cs
src/NetMQ/Core/Patterns/Pub.cs
src/NetMQ/Core/Patterns/Pull.cs
src/NetMQ/Core/Patterns/Push.cs
src/NetMQ/Core/Patterns/Rep.cs
src/NetMQ/Core/Patterns/Req.cs
src/NetMQ/Core/Patterns/Router.cs
src/NetMQ/Core/Patterns/Stream.cs
src/NetMQ/Core/Patterns/Sub.cs
src/NetMQ/Core/Patterns/XPub.cs
src/NetMQ/Core/Patterns/XSub.cs
src/NetMQ/Core/SessionBase.cs
src/NetMQ/Core/SocketBase.cs
src/NetMQ/Core/ZmqSocketOption.cs
src/NetMQ/SocketOptions.cs

When using ZMQ_HEARTBEAT one still needs to implement application-level heartbeat in order to know when to send a hello message.
For example, with the majordomo protocol, the worker needs to send a READY message when connecting to a broker. If the connection to the broker drops, and the heartbeat recognizes it the worker won't know about it and won't send the READY msg.
To solve that, the majordomo worker still has to implement heartbeat. With this new option, whenever the connection drops and reconnects the hello message will be sent, greatly simplify the majordomo protocol, as now READY and HEARTBEAT can be handled by zeromq.

problem: ZMQ_HEARTBEAT is not useful without sending an hello message

---

src/NetMQ/Core/Transports/Pgm/PgmSender.cs

Previously buffer was shifted by _aggregate_ amount on every loop iteration; should only be shifted by number of bytes encoded on that pass.

PgmSender Encoding Fix

---

src/NetMQ/Core/Transports/Pgm/PgmSession.cs

I've seen this far less frequently than the ConnectionReset, but from what I can tell from the documentation, this is also not a fatal error.  Given that it's hard to catch exceptions thrown in the IOThread, I prefer calling Error and continuing execution.  For context, I've been using this change for several years and have never seen any negative consequences.  (Totally acknowledged that I may've suppressed a critical issue and just missed it!)
Thanks very much!

PgmSession: Add handling for ConnectionAborted

---

src/NetMQ.Tests/ClientServer.cs
src/NetMQ/Core/CommandType.cs
src/NetMQ/Core/SocketBase.cs
src/NetMQ/Core/ZObject.cs
src/NetMQ/ReceiveThreadSafeSocketExtensions.cs
src/NetMQ/RoutingIdSocketExtensions.cs
src/NetMQ/ThreadSafeSocket.cs
src/NetMQ/ThreadSafeSocketExtensions.cs

Solution: add cancellation token to all receive operation (thread safe only, for now)

problem: no way to cancel receive operation

---

src/NetMQ/NetMQQueue.cs

This problem only existed in the non-generic interface implementation.

Fix bug in NetMQQueue.GetEnumerator

---

src/Directory.Build.props
src/NetMQ.sln

Work around a bug seen as a result of producing deterministic builds.
The error was:
> SourceRoot items must include at least one top-level (not nested) item when DeterministicSourcePaths is true

Fix design-time builds in VS

---

src/NetMQ.Tests/App.config
src/NetMQ.Tests/ThrowingTraceListener.cs

Previously, assertion failures while running unit tests would display a dialog box. This change causes an exception to be thrown instead.
This behaviour is beneficial on CI if debug builds are used.
The only downside is that locally it's a bit less convenient to investigate failures, as the 'retry' button allows quickly attaching a debugger with the offending frame in play.

Make System.Diagnostics.Debug failures throw in unit tests

---

AUTHORS.md
src/NetMQ/Core/Transports/StreamEngine.cs

Hello all,
I had an exception attached occurring when using PUB/SUB messaging pattern. The exception only occurrs when I access the publisher through a VPN. 
After some debugging I found out that I was having a SocketError.Shutdown which was not being handled by NetMQ. I have added an extra check to overcome this issue.
[NetMQException.txt](https://github.com/zeromq/netmq/files/4863241/NetMQException.txt)

Handle SocketError.Shutdown

---

src/NetMQ.Tests/OutgoingSocketExtensionsTests.cs
src/NetMQ/OutgoingSocketExtensions.cs

"TrySendFrame" thrown a System.ArgumentException if buffer was bigger than length

Fix TrySendFrame if buffer is bigger than length

---

src/NetMQ/NetMQ.csproj

Don't have to specify versions explicitly, can simply check for `TargetFrameworkIdentifier` instead.

Simplify .NET Framework conditional references

---

src/NetMQ/AsyncReceiveExtensions.cs

This PR updates ReceiveFrameBytesAsync to detach competing listeners before finishing the TaskCompletionSource and call `TrySetResult` and `TrySetCanceled` instead of `SetResult` and `SetCanceled`.
Fixes #965.

Fix cancellation in ReceiveFrameBytesAsync

---

src/NetMQ/NetMQBeacon.cs

Catches exception that occurs when a UDP message larger than 255 appears on the beacon's port and ignores it.
Reproduce by sending a message on a given UDP port when the beacon is listening on it that is larger than 255 bytes.
FATAL { 2021-05-13 16:20:31,295 [NetMQActor-4640-3863] } - Fatal unhandled exception thrown, runtime terminating=True
System.Net.Sockets.SocketException (0x80004005): A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself
at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
at NetMQ.NetMQBeacon.Shim.ReceiveUdpFrame(String& peerName)
at …

Catch small buffer Exception Beacon

---

src/NetMQ/Core/Transports/V1Decoder.cs

Solution to resolve this error:
System.OverflowException: Array dimensions exceeded supported range.
at NetMQ.GCBufferPool.Take(Int32 size)
at NetMQ.Msg.InitPool(Int32 size)
at NetMQ.Core.Transports.V1Decoder.EightByteSizeReady()
at NetMQ.Core.Transports.DecoderBase.Decode(ByteArraySegment data, Int32 size, Int32& bytesUsed)
at NetMQ.Core.Transports.StreamEngine.ProcessInput()
at NetMQ.Core.Transports.StreamEngine.FeedAction(Action action, SocketError socketError, Int32 bytesTransferred)
at NetMQ.Core.Utils.Proactor.Loop()

fix: fixed error System.OverflowException: Array dimensions exceeded supported range.

---

src/NetMQ.Tests/MechanismTests.cs
src/NetMQ/Core/Mechanisms/Mechanism.cs
src/NetMQ/Core/Utils/Proactor.cs

Fixes #1049
The original code only verified the length after calling GetString, but never gets there if the subsequent call to encoding.GetString fails with an ArgumentOutOfRangeException. This change moves the verification to before the call to GetString.
The second commit modifies the Proactor.Loop method so that it does not trigger a process exit due to an unhandled exception when an error occurs. To this end, it no longer throws an ArgumentOutOfRangeException if an invalid completion status is encountered (incidentally, this is the same error thrown by the GetString method for the earlier bug), and it catches all exceptions to allow the loop to continue in case of a failure.

Fix issue where message is assumed to contain correct length byte (leading to process exit)

---

src/NetMQ/Core/MonitorEvent.cs
src/NetMQ/Core/Transports/Pgm/PgmSocket.cs
src/NetMQ/Core/Transports/Tcp/TcpAddress.cs
src/NetMQ/Core/Utils/Clock.cs
src/NetMQ/Core/Utils/OpCode.cs
src/NetMQ/Core/Utils/PollerBase.cs
src/NetMQ/NetMQBeacon.cs
src/NetMQ/NetMQException.cs

.NET Standard 1.6 support was removed in NetMQ 4.0.1.
* Remove unused conditional code for .NET Standard 1.6
* Keep `RuntimeInformation.IsOSPlatform` usage that only ran on .NET Standard 1.6 target

Remove .NET Standard 1.6 conditional code

---

src/NetMQ/Core/Utils/OpCode.cs
src/NetMQ/SocketOptions.cs

The implementations using an environment variable rather than a static flag on an unrelated class.
Fixes #1071

Avoid reading time stamp counter

---

src/NetMQ/Core/Patterns/Utils/FairQueueing.cs

As detailed in issue [#1088](https://github.com/zeromq/netmq/issues/1088), the `FairQueueing` class in NetMQ is prone to a `DivideByZeroException` when all inbound pipes are deactivated and `m_active` becomes zero. This issue occurs during the round-robin selection process in the `RecvPipe` method.
This pull request implements a conditional check to ensure that the modulo operation for round-robin scheduling is only performed when there is at least one active pipe (`m_active > 0`). This change prevents the system from attempting a division by zero, which can lead to an application crash under specific scenarios.
- Modified the round-robin index update line in `RecvPipe` method to:
```csharp
if (!m_more)
m_current = m_active > 0 ? (m_current + 1) % m_active : 0;

Fix Division by Zero in FairQueueing when m_active is 0

---

src/NetMQ/Core/Mailbox.cs

If DNS is not accessible we get the poller throwing:
```
Unhandled exception. System.Net.Sockets.SocketException (11): Resource temporarily unavailable
at System.Net.Sockets.Socket.Receive(Byte[] buffer)
at NetMQ.Core.Utils.Signaler.Recv()
at NetMQ.Core.Mailbox.TryRecv(Int32 timeout, Command& command)
at NetMQ.Core.SocketBase.ProcessCommands(Int32 timeout, Boolean throttle, CancellationToken cancellationToken)
at NetMQ.Core.SocketBase.GetSocketOption(ZmqSocketOption option)
at NetMQ.NetMQSelector.Select(Item[] items, Int32 itemsCount, Int64 timeout)
at NetMQ.NetMQPoller.RunPoller()
at NetMQ.NetMQPoller.Run(SynchronizationContext syncContext)
at NetMQ.NetMQPoller.Run()
at System.Threading.Thread.StartCallback()
```

Try catch for blocking recieve which can throw

---

.github/workflows/CI.yml
src/NetMQ.Tests/NetMQ.Tests.csproj

- [CY - YML] remove net3.1 and net 6 and update to use net9
- Update github actions to latest versions (checkout and setup-dotnet actions)

modernize repository

---

src/NetMQ/Core/Transports/Ipc/IpcAddress.cs
src/NetMQ/Utils/Strings.cs

Fixes #1080
The previous code used String.GetHashCode, however in .NET 5 and later this value is not stable across process runs. The value intentionally varies due to "hash randomization", a security feature.
In this case, we need a stable value, and we need the same value irrespective of the version of .NET or the platform.
To ensure compatibility, we take the algorithm from .NET Framework.

Use a stable hash function for computing IPC port

---

src/NetMQ.Tests/SocketOptionsTests.cs
src/NetMQ/Core/Options.cs
src/NetMQ/Core/Patterns/Peer.cs
src/NetMQ/Core/Patterns/Router.cs
src/NetMQ/Core/Patterns/Server.cs
src/NetMQ/Core/Pipe.cs
src/NetMQ/Core/SessionBase.cs
src/NetMQ/Core/SocketBase.cs
src/NetMQ/Core/Transports/Pgm/PgmSender.cs
src/NetMQ/Core/Transports/Pgm/PgmSession.cs
src/NetMQ/Core/Transports/StreamEngine.cs
src/NetMQ/Core/Transports/Tcp/TcpListener.cs
src/NetMQ/Core/ZmqSocketOption.cs
src/NetMQ/SocketOptions.cs
src/NetMQ/ThreadSafeSocketOptions.cs

Add Support for Disconnect Message
