zeromq/netmq

- src/NetMQ/zmq/Utils/OpCode.cs
Sub-optimal fix for Issue #199
> zmq/Utils/OpCode.cs: added test for mmap fail into Open() method

- src/NetMQ/NetMQ.csproj
- src/NetMQ/NetMQ3.5.csproj
- src/NetMQ/zmq/Utils/Poller.cs
- src/NetMQ/zmq/Utils/Selector.cs
- src/NetMQ/zmq/Utils/SocketUtility.cs
- src/NetMQ/zmq/Utils/SocketUtility3.5.cs
> fix dotnet35 high cpu issue

- src/NetMQ.Tests/BeaconTests.cs
- src/NetMQ/NetMQBeacon.cs
> fix bug in beacon

- src/NetMQ.Tests/NetMQSchedulerTest.cs
- src/NetMQ.sln.DotSettings
- src/NetMQ/NetMQScheduler.cs
- src/NetMQ/Proxy.cs
As with my other odd-bits PR, if any of these don't feel right, let me know and I can splice them out of the PR.
> Docs, validation, typo

- README.md
Adds the following icons to the README file:
[![NetMQ Team City Build](https://img.shields.io/teamcity/codebetter/bt1046.svg)](http://teamcity.codebetter.com/project.html?projectId=NetMQ) [![NetMQ NuGet version](https://img.shields.io/nuget/v/NetMQ.svg)](https://www.nuget.org/packages/NetMQ/) [![NetMQ download stats](https://img.shields.io/nuget/dt/NetMQ.svg)](https://www.nuget.org/packages/NetMQ/)
> Add build & nuget badges to README

- src/NetMQ.Tests/MessageTests.cs
- src/NetMQ.Tests/MonitorPollTests.cs
- src/NetMQ.Tests/PollerTests.cs
- src/NetMQ.Tests/PubSubTests.cs
- src/NetMQ.Tests/PushPullTests.cs
- src/NetMQ.Tests/ReqRepTests.cs
- src/NetMQ.Tests/RouterTests.cs
- src/NetMQ.Tests/SocketTests.cs
- src/NetMQ.Tests/StreamTests.cs
- src/NetMQ.Tests/XPubSubTests.cs
- src/NetMQ/zmq/SocketBase.cs
- src/NetMQ/zmq/Transports/Tcp/TcpListener.cs
This made the unit tests pass on my computer where ports in the 5000 range were not available.
Also fixed bug in #260.
> Fix Unbind of random port. Unit test use random ports.

- README.md
I think @somdoron mentioned C4.1 recently. Should we update the README?
> Mention and link to C4.1 process

- src/NetMQ.Tests/PollerTests.cs
- src/NetMQ/Monitoring/NetMQMonitor.cs
- src/NetMQ/NetMQScheduler.cs
- src/NetMQ/Poller.cs
Some IDisposables were not properly disposed.
> Fixed: IDisposables not being disposed.

- src/NetMQ.Tests/ActorTests.cs
- src/NetMQ.Tests/BeaconTests.cs
- src/NetMQ.Tests/Devices/DeviceTestBase.cs
- src/NetMQ.Tests/NetMQ.Tests.csproj
- src/NetMQ.Tests/PgmTests.cs
- src/NetMQ.Tests/ReceivingSocketExtensionsTests.cs
- src/NetMQ/InProcActors/Actor.cs
- src/NetMQ/Msg.cs
- src/NetMQ/NetMQActor.cs
- src/NetMQ/NetMQMessage.cs
- src/NetMQ/OutgoingSocketExtensions.cs
- src/NetMQ/Poller.cs
- src/NetMQ/ReceivingSocketExtensions.cs
Please review especially:
* 58cab65 fix for #272
* f6593a8 removal of destructors
> Fix #272. More unit tests. Some minor tidying.

- src/NetMQ.Tests/PollerTests.cs
- src/NetMQ.Tests/Security/SecureChannelTests.cs
- src/NetMQ.Tests/SocketTests.cs
- src/NetMQ/NetMQBeacon.cs
- src/NetMQ/ReceivingSocketExtensions.cs
- src/NetMQ/Security/V0_1/HandshakeLayer.cs
- src/NetMQ/Security/V0_1/SecureChannel.cs
- src/NetMQ/SocketOptions.cs
- src/NetMQ/Sockets/PublisherSocket.cs
- src/NetMQ/Sockets/RequestSocket.cs
- src/NetMQ/Sockets/ResponseSocket.cs
- src/NetMQ/zmq/Utils/Signaler.cs
- src/Samples/InterBrokerRouter/Program.cs
- src/Samples/Majordomo/MDPWorkerExample/Program.cs
- src/Samples/Majordomo/MajordomoProtocol/Contracts/IMDPBroker.cs
- src/Samples/Majordomo/MajordomoProtocol/Contracts/IMDPClient.cs
- src/Samples/Majordomo/MajordomoProtocol/Contracts/IMDPWorker.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPBroker.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPClient.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPWorker.cs
- src/Samples/Majordomo/MajordomoProtocol/Service.cs
- src/Samples/Majordomo/MajordomoProtocolTests/MDPClientTests.cs
- src/Samples/Majordomo/MajordomoProtocolTests/MDPWorkerTests.cs
Most of them were in the xmldocs and comments
> Fixed a few typos

- AUTHORS.md
- src/NetMQ.Tests/NetworkOrderBitsConverterTests.cs
- src/NetMQ/NetworkOrderBitsConverter.cs
As the title says. Not much more to it than that. I added a test method as well, and in addition fixed a typo with the existing tests' names. I have also added myself to the authors file as requested.
> 16-bit integer methods for NetworkOrderBitsConverter

- src/NetMQ/NetMQScheduler.cs
> Add documentation to NetMQScheduler.CanExecuteTakInline

- src/NetMQ/Devices/DeviceBase.cs
> adds initialize to DeviceBase

- src/NetMQ.Tests/SocketTests.cs
- src/NetMQ/Core/SocketBase.cs
sockets send own identity to self when connected to peer thus router
dealer pair will not work on the "inproc" transport
> fix "identity  himself" socket bug

- src/NetMQ/Core/Transports/Tcp/TcpListener.cs
> dispose accept socket when occur connection error.

- src/Samples/Pirate Pattern/Paranoid Pirate/StartParanoidPirate.bat
Sample .bat file in Paranoid Pirate.
> Queue Sample file path is not correct.

- src/NetMQ.Tests/Security/SecureChannelTests.cs
- src/NetMQ/Blob.cs
- src/NetMQ/Core/Ctx.cs
- src/NetMQ/Core/MonitorEvent.cs
- src/NetMQ/Core/Patterns/Utils/Distribution.cs
- src/NetMQ/Core/SocketBase.cs
- src/NetMQ/Core/Transports/IDecoder.cs
- src/NetMQ/Core/Transports/IEncoder.cs
- src/NetMQ/Core/Utils/Signaler.cs
- src/NetMQ/NetMQActor.cs
- src/NetMQ/NetMQFrame.cs
- src/NetMQ/Security/V0_1/HandshakeLayer.cs
- src/NetMQ/Security/V0_1/RecordLayer.cs
- src/NetMQ/SendReceiveConstants.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPBroker.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPWorker.cs
- src/Samples/Majordomo/MajordomoProtocolTests/MDPBrokerTests.cs
- src/Samples/Titanic Pattern/TitanicBroker/TitanicFileIO.cs
- src/Samples/Titanic Pattern/TitanicBroker/TitanicMemoryIO.cs
Small changes pulled out of the C# 6 PR (#366).
> Minor fixes

- src/NetMQ/NetMQ.nuspec
- src/NetMQ/Properties/AssemblyInfo.cs
I changed the assembly info version and release notes.
Once merged I will release it to nuget.
@drewnoakes what do you think?
> Prepare version 3.3.2.0

- src/NetMQ.Tests/OutgoingSocketExtensionsTests.cs
- src/NetMQ/OutgoingSocketExtensions.cs
> Modified SendMoreFrameEmpty to return socket so that it can be chained

- src/NetMQ/Core/Patterns/XPub.cs
> Add pipes queue for manual (un)sub and broadcast messages.

- src/NetMQ/Core/Patterns/XPub.cs
As described in #403. Sorry for many small PRs instead of a big one. With this change I have finally built a clone pattern using only XPub/XSub sockets. Will try to add a sample soon.
> Fix bug when broadcast and manual options are true at the same time

- src/NetMQ/Core/Utils/Switch.cs
- src/NetMQ/NetMQ.csproj
- src/NetMQ/NetMQ3.5.csproj
- src/NetMQ/Poller.cs
solution: check if the thread is started before returning from the method.
fix issue #409
> Problem: when poller started and immediately disposed exception is thrown

- src/NetMQ/NetMQQueue.cs
> IENumerable only

- src/NetMQ.Tests/SocketTests.cs
- src/NetMQ/Global.cs
- src/NetMQ/NetMQ.csproj
- src/NetMQ/NetMQ3.5.csproj
- src/NetMQ/NetMQSocket.cs
- src/NetMQ/Sockets/DealerSocket.cs
- src/NetMQ/Sockets/PairSocket.cs
- src/NetMQ/Sockets/PublisherSocket.cs
- src/NetMQ/Sockets/PullSocket.cs
- src/NetMQ/Sockets/PushSocket.cs
- src/NetMQ/Sockets/RequestSocket.cs
- src/NetMQ/Sockets/ResponseSocket.cs
- src/NetMQ/Sockets/RouterSocket.cs
- src/NetMQ/Sockets/StreamSocket.cs
- src/NetMQ/Sockets/SubscriberSocket.cs
- src/NetMQ/Sockets/XPublisherSocket.cs
- src/NetMQ/Sockets/XSubscriberSocket.cs
Suggested solution: global context, now sockets can be created without a context.
> Problem: context must be used to create sockets

- src/NetMQ/NetMQQueue.cs
> Fix bug in NetMQQueue

- src/NetMQ/Core/Patterns/Utils/Trie.cs
- src/NetMQ/Msg.cs
- src/NetMQ/NetMQSocket.cs
- src/NetMQ/OutgoingSocketExtensions.cs
- src/NetMQ/ReceivingSocketExtensions.cs
- src/NetMQ/Security/V0_1/RecordLayer.cs
- src/NetMQ/Security/V0_1/SecureChannel.cs
Address all warnings seen during `Release` build.
> XML documentation fixes

- src/NetMQ.Zyre.Tests/NetMQ.Zyre.Tests.csproj
- src/NetMQ.Zyre.Tests/Properties/AssemblyInfo.cs
- src/NetMQ.Zyre.Tests/ZreMsgTests.cs
- src/NetMQ.Zyre/NetMQ.Zyre.csproj
- src/NetMQ.Zyre/Properties/AssemblyInfo.cs
- src/NetMQ.Zyre/ZreMsg.cs
- src/NetMQ.Zyre/_ReadMe.txt
- src/NetMQ.Zyre/packages.config
- src/NetMQ.Zyre/zproto/Example.xml
- src/NetMQ.Zyre/zproto/Generate.bat
- src/NetMQ.Zyre/zproto/License.xml
- src/NetMQ.Zyre/zproto/zproto_codec_cs.gsl
- src/NetMQ.Zyre/zproto/zproto_lib.gsl
- src/NetMQ.Zyre/zproto/zproto_lib_cs.gsl
- src/NetMQ.Zyre/zproto/zre_msg.xml
- src/NetMQ.sln
* I was unsuccessful with include filename = "License.xml in zre_msg.xml. Gives me an error: 
* (zproto_lib.gsl 90) Undefined expression: class.load_file (...)
* The generated ZreMsgTests still are using NetMQContext. I didn't try to figure out where to fix this.
* Two of the generated ZreMsgTests unit tests fail. I didn't investigate.
* We could make the generation of ZreMsg a Pre-build event. Is it worthwhile for a file that seldom changes?
> Net mq.zyre

- docs/pub-sub.md
The samples need NetMQ.Sockets in the using section.
> Added NetMQ.Sockets to samples

- src/NetMQ.Tests/NetMQPollerTest.cs
- src/NetMQ/NetMQ.nuspec
- src/NetMQ/Properties/AssemblyInfo.cs
also add category to poller tests
> Update version to version 4

- src/NetMQ.Tests/RouterTests.cs
- src/NetMQ/Core/Patterns/Router.cs
- src/NetMQ/Core/ZmqSocketOption.cs
- src/NetMQ/SocketOptions.cs
solution: port router handover from libzmq, with router handover if socket with same identity already exist the new socket will take over.
> problem: when dealer with identity set reconnect to router connection might be rejected

- src/NetMQ.Tests/RouterTests.cs
- src/NetMQ/Core/Patterns/Router.cs
- src/NetMQ/Core/Pipe.cs
> problem: when using mandatory router blocks instead of throwing exception

- src/NetMQ/Core/SessionBase.cs
- src/NetMQ/Core/Transports/Pgm/PgmSender.cs
- src/NetMQ/Core/Transports/Pgm/PgmSocket.cs
- src/NetMQ/Core/Transports/StreamEngine.cs
> Fix PGM and ZMQ2.2 issues

- src/NetMQ/Core/Patterns/XPub.cs
- src/NetMQ/Core/Patterns/XSub.cs
- src/NetMQ/OutgoingSocketExtensions.cs
This addresses #504. No explicit tests yet, but I use these changes for several days already.
> Add support for multi-part messages starting with 1 or 0 in XPub/XSub

- AUTHORS.md
- src/NetMQ/Devices/DeviceBase.cs
- src/NetMQ/INetMQPoller.cs
- src/NetMQ/ISocketPollableCollection.cs
- src/NetMQ/Monitoring/NetMQMonitor.cs
- src/NetMQ/NetMQBeacon.cs
- src/NetMQ/NetMQConfig.cs
- src/NetMQ/NetMQException.cs
- src/NetMQ/NetMQPoller.cs
- src/NetMQ/NetMQQueue.cs
- src/NetMQ/NetMQSocket.cs
- src/NetMQ/PollEvents.cs
- src/NetMQ/Security/NetMQSecurityException.cs
- src/NetMQ/SendReceiveConstants.cs
- src/NetMQ/SocketEvents.cs
- src/NetMQ/SocketOptions.cs
- src/NetMQ/Sockets/PullSocket.cs
- src/NetMQ/Sockets/RequestSocket.cs
- src/NetMQ/Sockets/SubscriberSocket.cs
Solution: Remove most warnings. The few left were beyond my knowledge of NetMQ.
> Problem: Building in Release emit Warnings

- src/NetMQ.Tests/XPubSubTests.cs
- src/NetMQ/Core/Patterns/XPub.cs
Addresses #499.
Main points:
* Last pipe is stored all the time and is destroyed (set to null) on every Subscribe/Unsubscribe/Send. (Previously, it was set only on manual sub/unsub and on broadcast);
* We reuse pipe.Identity property and options.Identity properties to set an identity of a subscriber;
* One could set and get a subscriber identity via `publisher.Options.Identity : byte[]`;
* There is a unit test for subscriber ids.
https://github.com/zeromq/netmq/issues/499
> XPub could track subscribers by a custom ID

- src/NetMQ/Core/MonitorEvent.cs
Fix for https://github.com/zeromq/netmq/issues/528
> Check m_addr for null in MonitorEvent.Write

- docs/actor.md
- docs/message.md
- docs/poller.md
- docs/transports.md
Updated a few code samples to match the current API.
> Updated a few code samples in the documentation

- src/NetMQ/Core/SocketBase.cs
> problem: when closing socket sometime exception is thrown

- src/NetMQ/Core/MonitorEvent.cs
- src/NetMQ/Core/Transports/Tcp/TcpConnector.cs
- src/NetMQ/Core/Utils/Proactor.cs
See commit comments for details.
> Various fixes related to NetMQMonitor and TcpConnector

- src/NetMQ.sln
- src/Samples/Majordomo/MDPClientAsyncExample/App.config
- src/Samples/Majordomo/MDPClientAsyncExample/MDPClientAsyncExample.csproj
- src/Samples/Majordomo/MDPClientAsyncExample/MDPClientAsyncExampleProgram.cs
- src/Samples/Majordomo/MDPClientAsyncExample/Properties/AssemblyInfo.cs
- src/Samples/Majordomo/MDPClientExample/MDPClientExample.csproj
- src/Samples/Majordomo/MDPCommons/IMDPClientAsync.cs
- src/Samples/Majordomo/MDPCommons/MDPCommons.csproj
- src/Samples/Majordomo/MDPCommons/MDPConstants.cs
- src/Samples/Majordomo/MDPCommons/MDPReplyEventArgs.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPBroker.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPClient.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPClientAsync.cs
- src/Samples/Majordomo/MajordomoProtocol/MDPWorker.cs
- src/Samples/Majordomo/MajordomoProtocol/MajordomoProtocol.csproj
- src/Samples/Majordomo/MajordomoProtocolTests/MDPClientAsyncTests.cs
I've introduced at Majordomo sample the ClientAsync that uses DEALER instead of REQ
For now is a simple async sample, without  great reliability. I intend to improve reliability in near future this, with a mechanism that tracks outgoing requests and retry those that failed to be sent.
Resume of changes:
- Small refactor to constants variables 
- Added ClientAsync API
- Implemented ClientAsync (without retry mechanism)
- Added unit tests to new ClientAsync
- Added ClientAsyncExample console app program
> First version of Majordomo with async Clients (without retries)

- .github/ISSUE_TEMPLATE.md
Many issues we see don't include details of the NetMQ version, OS, etc. Hopefully this template will make it easier to identify what's going on.
This is just a first draft of this template. Please amend as needed.
> Add ISSUE_TEMPLATE file to encourage more detail in error reports

- docs/cleanup.md
- src/NetMQ.sln
- src/NetMQ/NetMQConfig.cs
also fixing small issue in docs
> problem: Config props are ignored

- src/NetMQ/Core/MonitorEvent.cs
- src/NetMQ/Core/Transports/Pgm/PgmSocket.cs
- src/NetMQ/Core/Transports/Tcp/TcpAddress.cs
- src/NetMQ/Core/Utils/Clock.cs
- src/NetMQ/Core/Utils/OpCode.cs
- src/NetMQ/Core/Utils/PollerBase.cs
- src/NetMQ/NetMQBeacon.cs
- src/NetMQ/NetMQException.cs
- src/NetMQ/project.json
- Change netstandard 1.6 -> netstandard 1.3
- Update projectUrl location issue project.json
> Relax netstandard platform requirement

- .travis.yml
- src/NetMQ-Core.sln
- src/NetMQ/Core/Transports/Tcp/TcpListener.cs
- src/NetMQ/project.json
Also added Travis CI, tests are still not passing but it should work. 
(Tests are failing on port already in use because of previous tests).
Ready to be merged, working on another PR of fixing the tests.
> Fix NetMQ not working Linux with dotnet core

- .travis.yml
- src/NetMQ.Tests/BeaconTests.cs
- src/NetMQ.Tests/NetMQPollerTest.cs
- src/NetMQ.Tests/NetworkOrderBitsConverterTests.cs
- src/NetMQ.Tests/PgmTests.cs
- src/NetMQ.Tests/RequestWithRetryTests.cs
- src/NetMQ.Tests/RouterTests.cs
- src/NetMQ.Tests/SocketTests.cs
- src/NetMQ.Tests/project.json
please let the CIs runs.
Travis should build dontet core on Linux...
> Fix tests on travis CI

- src/NetMQ/NetMQPoller.cs
- src/NetMQ/NetMQSelector.cs
- src/NetMQ/NetMQSocket.cs
Expose internal selector class for advanced usages of polling
> problem: Polling once with NetMQPoller is complicated

- src/NetMQ/Core/Transports/Tcp/TcpConnector.cs
> Added SocketError.OperationAborted to list of recoverable errors

- docs/cleanup.md
Here are some minor grammar fixes that should help improve the readability.
> minor grammar and punctuation fixes

- src/NetMQ/Core/Transports/Pgm/PgmListener.cs
> Issue #636: Fix Bind Exception on bound pgm Subscribers when cable is unplugged or plugged in again

- src/NetMQ/NetMQPoller.cs
> Add ContainsAsync methods to NetMQPoller

- src/NetMQ/OutgoingSocketExtensions.cs
> change spelling wether -> whether

- src/NetMQ/NetMQBeacon.cs
Because windows and unix differ in how they handle broadcast addressing
this needs to be platform specific.  On windows any interface can
recieve broadcast by requesting to enable broadcast on the socket. On
linux to recieve broadcast you must bind to the broadcast address
specifically. Verfied using Ubuntu-16.04 mono-5.02.
> Changed beacon receiving to work in unix

- src/NetMQ/NetMQ.csproj
So when CI try to release a version we will pick the right one.
> problem: when converting to csproj we didn't specify the version with in the csproj

- docs/pub-sub.md
> Pub/Sub sample binds * not localhost

- src/NetMQ/NetMQPoller.cs
This is the sort of thing I have in mind.  This is backward compatible with any existing code, and shouldn't cause any behavioural changes to existing applications.
> Allow user to specify custom sync context

- docs/push-pull.md
sink is pull-socket, not push socket
> Update push-pull.md, Fix wrong variable type

- src/NetMQ/Msg.cs
> Fixed #774, Update attributes in function Msg.Put

- appveyor.yml
- src/NetMQ.Tests/AsyncTests.cs
- src/NetMQ.Tests/NetMQ.Tests.csproj
- src/NetMQ/AsyncReceiveExtensions.cs
- src/NetMQ/NetMQ.csproj
- src/NetMQ/NetMQBeacon.cs
- src/NetMQ/NetMQPoller.cs
- src/NetMQ/NetMQRuntime.cs
- src/NetMQ/NetMQSocket.cs
- src/NetMQ/NetMQSynchronizationContext.cs
Solution: Add ReceiveAsync (and some overloads) to socket. Also, a NetMQRuntime must be created and run in order to signal the completion of the tasks
> Problem: NetMQ cannot be used with async/await pattern

- src/NetMQ/INetMQSocket.cs
- src/NetMQ/NetMQSocket.cs
Add Interface to NetMqSocket  to simplify mocking and unit testing.
https://github.com/zeromq/netmq/issues/99
https://github.com/zeromq/netmq/issues/63
> Add interface for NetMqSocket to simplify mocking (#63 and #99)

- docs/cleanup.md
This PR fixes typo in docs that describe cleanup.
> Fix typo in cleanup docs

- src/NetMQ/Core/Utils/Poller.cs
This fixes #806.
Currently, `Socket.Select` does not work properly on macOS .NET Core when `readList` and `errorList` are passed together. To avoid this problem, I changed to call the `Select` function separately for `errorList`.
Please refer to this issue: https://github.com/dotnet/corefx/issues/39617
> Fix problem where Cleanup hangs on macOS .NET Core

- src/NetMQ/Msg.cs
> Publish is leaking msgs because of shared msg bug

- README.md
- appveyor.yml
In this PR, *codecov* was applied to resolve #784, with reference [codecov/example-csharp].
I expect the stats of coverage will be shown in README like below. 
It is only tested in my environment, so it is not clear if it will work. but it expects to work well.
[codecov/example-csharp]: https://github.com/codecov/example-csharp
> Apply codecov

- .github/workflows/CI.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
> problem: windows and linux builds are split over two services

- src/NetMQ.Tests/ReqRepTests.cs
- src/NetMQ/Core/Options.cs
- src/NetMQ/Core/Patterns/Dealer.cs
- src/NetMQ/Core/Patterns/Peer.cs
- src/NetMQ/Core/Patterns/Req.cs
- src/NetMQ/Core/Patterns/Router.cs
- src/NetMQ/Core/Patterns/Stream.cs
- src/NetMQ/Core/Patterns/Utils/FairQueueing.cs
- src/NetMQ/Core/Patterns/Utils/LoadBalancer.cs
- src/NetMQ/Core/ZmqSocketOption.cs
- src/NetMQ/SocketOptions.cs
Also added appropriate unit testing.
Fixed awkward treatement of the pipe variable in FairQueueing.RecvPipe
> Added support for ZMQ_REQ_CORRELATE and ZMQ_REQ_RELAXED socket options

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- appveyor.yml
Also fix the capitalisation of the argument used by AppVeyor.
> Add ContinuousIntegrationBuild property for GitHub actions

- src/NetMQ.sln.DotSettings
Makes ReSharper a bit happier with some files.
> Add some words to the dictionary

- src/Directory.Build.props
- src/NetMQ.Tests/NetMQ.Tests.csproj
- src/NetMQ/NetMQ.csproj
- src/Performance/NetMQ.SimpleTests/NetMQ.SimpleTests.csproj
- src/Performance/local_thr/local_thr.csproj
This package is used by most projects. Adding it centrally has no downside as it has PrivateAssets all anyway.
Bumps package to the latest version, 2020.1.0.
> Add JetBrains.Annotations centrally

- src/NetMQ/NetMQPoller.cs
Marking the Poller thread a background thread since the process hosting this poller is not shutting down.
> Provision to have override long running poller 

- src/NetMQ/NetMQPoller.cs
To fix issue described in https://github.com/zeromq/netmq/issues/926
> Fixed comment about background thread.

- src/NetMQ/Msg.cs
> Issue #978 expose internal buffer as memory<byte> #1

- src/NetMQ.Tests/NetMQ.Tests.csproj
> Bump Newtonsoft.Json in response to security advisory

- src/Directory.Build.props
- src/NetMQ/NetMQ.csproj
Removes dependencies which are already available as part of the library
Closes #1090
> #1090 Leverage Framework Libraries
